# Generated by Django 5.1.4 on 2025-01-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="option_name",
            new_name="options",
        ),
    ]
