# Generated by Django 5.1.4 on 2025-01-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_option_name_option_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="options",
            new_name="optionname",
        ),
    ]
